# Generated by Django 5.2.4 on 2025-07-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
